mywebsite/authentification/urls.py
from django.urls import path
from . import views as auth_views
from . import api_views

urlpatterns = [
    path('signup/', auth_views.signup, name='signup'),
    path('signin/', auth_views.signin, name='signin'),
    path('signout/', auth_views.signout, name='signout'),
    path('contactList/', auth_views.contact, name='contactList'),
    path('send_friend_request/', auth_views.send_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:friend_request_id>/', auth_views.accept_friend_request, name='accept_friend_request'),
    path('refuse_friend_request/<int:friend_request_id>/', auth_views.refuse_friend_request, name='refuse_friend_request'),
    path('cancel_friend_request/<int:friend_request_id>/', auth_views.cancel_friend_request, name='cancel_friend_request'),
    path('remove_friend/<int:friend_id>/', auth_views.remove_friend, name='remove_friend'),
    path('update_profile/', auth_views.update_profile, name='update_profile'),
    path('delete_profile/', auth_views.delete_profile, name='delete_profile'),
    path('update_password/', auth_views.update_password, name='update_password'),
    path('request_anonymization/', auth_views.request_anonymization, name='request_anonymization'),

    # SSE view
    path('sse/', auth_views.sse, name='sse'),
    # path('sse_test/', auth_views.sse_test, name='sse_test'),

    # API URLs last
    path('oauth/complete/42/', api_views.callback_42, name='callback_42'),
]

mywebsite/frontend/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.home, name='index'),
	path('home/', views.home, name='home'),
	path('login/', views.login, name='login'),
	path('signup/', views.signup, name='signup'),
	path('profile/', views.profile, name='profile'),
	path('edit_profile/', views.edit_profile, name='edit_profile'),
	path('edit_password/', views.edit_password, name='edit_password'),
	path('games/', views.games, name='games'),
	path('leaderboard/', views.leaderboard, name='leaderboard'),
	path('dashboard/<str:username>/', views.user_dashboard, name='user_dashboard'),
	path('load_header/', views.load_header, name='load_header'),
	path('contact/', views.contact, name='contact'),
	path('deleted_profile/', views.deleted_profile, name='deleted_profile'),
	path('error_api/', views.error_api, name='error_api'),
]

mywebsite/mywebsite/urls.py
from django.contrib import admin
from django.urls import include, path
# import django_eventstream

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('pong/', include('pong.urls')),
    path('invaders/', include('invaders.urls')),
    # path('auth/', include('authentification.urls')),
	path('auth/', include(('authentification.urls', 'authentification'), namespace='authentification')),
    # path("events/", include(django_eventstream.urls)),
]

mywebsite/pong/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.pong),
]

mywebsite/frontend/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('email', 'first_name', 'last_name', 'display_name', 'password1', 'password2', 'avatar')

# class CustomAuthenticationForm(AuthenticationForm):
# 	class Meta:
# 		model = CustomUser
# 		fields = ('email', 'password')

mywebsite/frontend/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.db.models import Max, Avg
from .models import PlayerMatch, CustomUser

def index(request):
	redirect('home')

def home(request):
	if request.headers.get('x-requested-with') == 'XMLHttpRequest':
		html = render_to_string('home.html', request=request)
		return JsonResponse({'html': html})
	return render(request, 'base.html')

def login(request):
	context = {
		'api_42_auth_url': settings.API_42_AUTH_URL
	}
	if request.headers.get('x-requested-with') == 'XMLHttpRequest':
		html = render_to_string('login.html', context, request=request)
		return JsonResponse({'html': html})
	return render(request, 'base.html')

def signup(request):
	if request.headers.get('x-requested-with') == 'XMLHttpRequest':
		html = render_to_string('signup.html', request=request)
		return JsonResponse({'html': html})
	return render(request, 'base.html')

def contact(request):
	if request.headers.get('x-requested-with') == 'XMLHttpRequest':
		html = render_to_string('contact.html', request=request)
		return JsonResponse({'html': html})
	return render(request, 'base.html')

def deleted_profile(request):
	if request.headers.get('x-requested-with') == 'XMLHttpRequest':
		html = render_to_string('deleted_profile.html', request=request)
		return JsonResponse({'html': html})
	return render(request, 'base.html')

def error_api(request):
	if request.headers.get('x-requested-with') == 'XMLHttpRequest':
		html = render_to_string('error_api.html', request=request)
		return JsonResponse({'html': html})
	return render(request, 'base.html')

@login_required
def profile(request):
	pending_requests = request.user.get_pending_friend_requests()
	sent_requests = request.user.get_sent_friend_requests()
	context = {
		'pending_requests': pending_requests,
		'sent_requests': sent_requests
	}
	if request.headers.get('x-requested-with') == 'XMLHttpRequest':
		html = render_to_string('profile.html', context, request=request)
		return JsonResponse({'html': html})
	return render(request, 'base.html')

@login_required
def edit_profile(request):
	predefined_avatars = [
		{"url": "../media/img/avatars/avatar0.jpg"},
		{"url": "../media/img/avatars/avatar1.jpg"},
		{"url": "../media/img/avatars/avatar2.jpg"},
		{"url": "../media/img/avatars/avatar3.jpg"},
		{"url": "../media/img/avatars/avatar4.jpg"},
		{"url": "../media/img/avatars/avatar5.jpg"},
		{"url": "../media/img/avatars/avatar6.jpg"},
	]

	if request.headers.get('x-requested-with') == 'XMLHttpRequest':
		html = render_to_string('edit_profile.html', {'predefined_avatars': predefined_avatars}, request=request)
		return JsonResponse({'html': html})
	return render(request, 'base.html', {'predefined_avatars': predefined_avatars})

@login_required
def edit_password(request):
	if request.headers.get('x-requested-with') == 'XMLHttpRequest':
		html = render_to_string('edit_password.html', request=request)
		return JsonResponse({'html': html})
	return render(request, 'base.html')

def games(request):
	if request.headers.get('x-requested-with') == 'XMLHttpRequest':
		html = render_to_string('games.html', request=request)
		return JsonResponse({'html': html})
	return render(request, 'base.html')

@login_required
def leaderboard(request):
	players = PlayerMatch.objects.filter(match__game__name="Pong").values('player').distinct()

	pong_leaderboard = []

	for player_data in players:
		player = player_data['player']
		player_instance = CustomUser.objects.get(id=player)
		victories = PlayerMatch.objects.filter(player=player_instance, match__game__name="Pong", is_winner=True).count()
		defeats = PlayerMatch.objects.filter(player=player_instance, match__game__name="Pong", is_winner=False).count()
		pong_leaderboard.append((player_instance.display_name, victories, defeats))

	pong_leaderboard = sorted(pong_leaderboard, key=lambda x: (-x[1], x[2]))[:5]

	leaderboard_data = PlayerMatch.objects.select_related('player', 'match').order_by('-score')
	invaders_leaderboard = []
	invaders_rank = 1

	for entry in leaderboard_data:
		if entry.match.game.name == "Invaders":
			invaders_leaderboard.append((invaders_rank, entry))
			invaders_rank += 1
		if invaders_rank > 5:
			break

	context = {
		'pong_leaderboard': pong_leaderboard,
		'invaders_leaderboard': invaders_leaderboard,
	}

	if request.headers.get('x-requested-with') == 'XMLHttpRequest':
		html = render_to_string('leaderboard.html', context, request=request)
		return JsonResponse({'html': html})

	return render(request, 'base.html', context)

@login_required
def user_dashboard(request, username):
	user = get_object_or_404(CustomUser, display_name=username)
	dashboard_data = PlayerMatch.objects.select_related('player', 'match').filter(player__display_name=user.display_name).order_by('-match__date')

	total_matches = dashboard_data.filter(match__game__name="Pong").count()
	victories = dashboard_data.filter(match__game__name="Pong", is_winner=True).count()
	defeats = dashboard_data.filter(match__game__name="Pong", is_winner=False).count()

	win_rate = (victories / total_matches * 100) if total_matches > 0 else 0

	pong_stats = {
		'total_matches': total_matches,
		'victories': victories,
		'defeats': defeats,
		'win_rate': round(win_rate, 2)
	}

	invaders_stats = {
		'total_matches': dashboard_data.filter(match__game__name="Invaders").count(),
		'average': dashboard_data.filter(match__game__name="Invaders").aggregate(Avg('score'))['score__avg'],
		'max_score': dashboard_data.filter(match__game__name="Invaders").aggregate(Max('score'))['score__max'],
		'last_five_scores': list(dashboard_data.filter(match__game__name="Invaders").order_by('-match__date').values_list('score', flat=True)[:5])
	}

	context = {
		'user_profile': user,
		'pong_stats': pong_stats,
		'invaders_stats': invaders_stats,
		'dashboard_data': dashboard_data,
	}

	if request.headers.get('x-requested-with') == 'XMLHttpRequest':
		html = render_to_string('dashboard.html', context, request=request)
		return JsonResponse({'html': html, 'pong_stats': pong_stats, 'invaders_stats': invaders_stats})

	return render(request, 'base.html', context)

def load_header(request):
	if request.headers.get('x-requested-with') == 'XMLHttpRequest':
		html = render_to_string('header.html', request=request)
		return JsonResponse({'html': html})
	return render(request, 'base.html')

mywebsite/frontend/templates/deleted_profile.html
{% load static %}
<section class="d-flex align-items-center justify-content-center mt-5">
	<div class="container mb-2 text-center">
		<div class="row justify-content-center">
			<div class="col-12 col-md-8 col-lg-6">
				<div class="card shadow-lg p-4">

					<div class="mb-4">
						<img src="{% static 'img/pusheen_sighing.gif' %}" alt="Sad Pusheen" class="img-fluid" style="max-width: 250px;">
					</div>

					<h1 class="text-danger mb-3">Account Deleted</h1>
					<p class="lead">We’re sad to see you go, but your account has been successfully deleted.</p>
					<p>If you ever change your mind, we’ll always be here to welcome you back!</p>

					<a href="/" class="btn btn-primary btn-lg mt-4" id="home-from-deleted">
						<i class="bi bi-house-door"></i> Back to Home
					</a>
				</div>
			</div>
		</div>
	</div>
</section>

mywebsite/frontend/templates/edit_password.html
{% load static %}
<section class="d-flex align-items-center justify-content-center mt-5">
	<div class="container mb-5">
		<div class="row justify-content-center mt-2 g-3">
			<div class="col-12 col-lg-8">
				<div class="card shadow rounded-4">
					<div class="card-header text-center bg-primary font-potta rounded-top-4">
						<h2>Edit Password</h2>
					</div>
					<div class="card-body p-5">
						<form id="edit-password-form" method="POST" action="{% url 'authentification:update_password' %}">
							{% csrf_token %}
							<div class="form-group mb-3">
								<label for="old_password">Current Password:</label>
								<input type="password" id="old_password" name="old_password" class="form-control rounded-3" required>
							</div>
							<div class="form-group mb-3">
								<label for="new_password1">New Password:</label>
								<input type="password" id="new_password1" name="new_password1" class="form-control rounded-3" required>
							</div>
							<div class="form-group mb-3">
								<label for="new_password2">Confirm New Password:</label>
								<input type="password" id="new_password2" name="new_password2" class="form-control rounded-3" required>
							</div>
							<button type="submit" class="btn btn-primary w-100">Change Password</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

mywebsite/frontend/templates/edit_profile.html
{% load static %}
<section class="d-flex align-items-center justify-content-center mt-5">
	<div class="container mb-5">
		<div class="row justify-content-center mt-2 g-3">
			<div class="col-12 col-lg-8">
				<div class="card shadow rounded-4">
					<div class="card-header text-center bg-primary font-potta rounded-top-4">
						<h2 class="font-balsamiq text-secondary-emphasis">Edit Profile</h2>
					</div>
					<div class="card-body p-5 text-secondary-emphasis">
						<form id="edit-profile-form" method="POST" enctype="multipart/form-data" action="{% url 'authentification:update_profile' %}">
							{% csrf_token %}
							<div class="form-group mb-3">
								<label for="first_name" style="opacity: 0.7;">First Name:</label>
								<input type="text" id="first_name" name="first_name" class="form-control text-secondary-emphasis" value="{{ user.first_name }}" required>
							</div>

							<div class="form-group mb-3">
								<label for="last_name" style="opacity: 0.7;">Last Name:</label>
								<input type="text" id="last_name" name="last_name" class="form-control text-secondary-emphasis" value="{{ user.last_name }}" required>
							</div>

							<div class="form-group mb-3">
								<label for="display_name" style="opacity: 0.7;">Display Name:</label>
								<input type="text" id="display_name" name="display_name" class="form-control text-secondary-emphasis" value="{{ user.display_name }}" required>
							</div>

							<div class="form-group mb-3">
								<div class="d-flex justify-content-center">
									<input type="radio" class="btn-check" name="avatar_option" id="predefined-option" autocomplete="off" checked>
									<label class="btn btn-secondary text-secondary-emphasis me-3" for="predefined-option" data-bs-toggle="collapse" data-bs-target="#predefined-avatars" aria-expanded="true" aria-controls="predefined-avatars" onclick="document.getElementById('upload-avatar').classList.remove('show')">Choose a New Avatar</label>

									<input type="radio" class="btn-check" name="avatar_option" id="upload-option" autocomplete="off">
									<label class="btn btn-secondary text-secondary-emphasis" for="upload-option" data-bs-toggle="collapse" data-bs-target="#upload-avatar" aria-expanded="false" aria-controls="upload-avatar" onclick="document.getElementById('predefined-avatars').classList.remove('show')">Upload Avatar</label>
								</div>
							</div>

							<div id="predefined-avatars" class="collapse form-group mb-3 show">
								<label for="avatar">Choose a new avatar:</label>
								<div class="d-flex flex-wrap justify-content-start">
									{% for avatar in predefined_avatars %}
									<label class="avatar-option me-3 mb-3 mb-md-0">
										<input type="radio" name="avatar_choice" value="{{ avatar.url }}" {% if user.avatar.url == avatar.url %}checked{% endif %}>
										<img src="{{ avatar.url }}" alt="Predefined avatar" class="img-thumbnail img-fluid" style="width: 100px; height: 100px;">
									</label>
									{% endfor %}
								</div>
							</div>

							<div id="upload-avatar" class="collapse form-group mb-3 text-secondary-emphasis">
								<label for="avatar">Upload your own avatar:</label>
								<input type="file" id="avatar" name="avatar" class="form-control">
							</div>

							<button type="submit" class="btn btn-primary w-100">Save Changes</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

mywebsite/frontend/templates/edit_profile2.html
{% load static %}
<section class="d-flex align-items-center justify-content-center mt-5">
	<div class="container mb-5">
		<div class="row justify-content-center mt-2 g-3">
			<div class="col-12 col-lg-8">
				<div class="card shadow rounded-4">
					<div class="card-header text-center bg-primary font-potta rounded-top-4">
						<h2>Edit Profile</h2>
					</div>
					<div class="card-body p-5">
						<form id="edit-profile-form" method="POST" enctype="multipart/form-data" action="{% url 'authentification:update_profile' %}">
							{% csrf_token %}
							<!-- <div class="form-group mb-3">
								<label for="email">Email:</label>
								<input type="email" id="email" name="email" class="form-control" value="{{ user.email }}" required>
							</div> -->

							<div class="form-group mb-3">
								<label for="first_name">First Name:</label>
								<input type="text" id="first_name" name="first_name" class="form-control" value="{{ user.first_name }}" required>
							</div>

							<div class="form-group mb-3">
								<label for="last_name">Last Name:</label>
								<input type="text" id="last_name" name="last_name" class="form-control" value="{{ user.last_name }}" required>
							</div>

							<div class="form-group mb-3">
								<label for="display_name">Display Name:</label>
								<input type="text" id="display_name" name="display_name" class="form-control" value="{{ user.display_name }}" required>
							</div>

							<!-- <div class="form-group mb-3">
								<label for="avatar">Choose a new avatar:</label>
								<div class="d-flex flex-wrap justify-content-start">
									{% for avatar in predefined_avatars %}
									<label class="avatar-option me-3 mb-3 mb-md-0">
										<input type="radio" name="avatar_choice" value="{{ avatar.url }}" {% if user.avatar.url == avatar.url %}checked{% endif %}>
										<img src="{{ avatar.url }}" alt="Your avatar" class="img-thumbnail img-fluid" style="width: 100px; height: 100px;">
									</label>
									{% endfor %}
								</div>
							</div>

							<div class="form-group mb-3">
								<label for="avatar">Or upload your own avatar:</label>
								<input type="file" id="avatar" name="avatar" class="form-control">
							</div> -->

							<div class="form-group mb-3">
								<label>Choose a new avatar:</label>
								<div class="d-flex flex-wrap justify-content-start">
									{% for avatar in predefined_avatars %}
									<label class="avatar-option me-3 mb-3 mb-md-0">
										<input type="radio" name="avatar_choice" value="{{ avatar.url }}" class="form-check-input" id="avatar_{{ forloop.counter }}"
										{% if user.avatar.url == avatar.url %}checked{% endif %}
										onchange="toggleCustomAvatar(false)">
										<img src="{{ avatar.url }}" alt="Your avatar" class="img-thumbnail img-fluid" style="width: 100px; height: 100px;">
									</label>
									{% endfor %}
									<!-- Adding a 'None' or 'Custom' option -->
									<label class="avatar-option me-3 mb-3 mb-md-0">
										<input type="radio" name="avatar_choice" value="custom" class="form-check-input" id="custom-avatar-choice"
										{% if not user.avatar.url in predefined_avatars %}checked{% endif %}
										onchange="toggleCustomAvatar(true)">
										<span>Custom Avatar</span>
									</label>
								</div>
							</div>
							<div class="form-group mb-3">
								<label for="avatar">Upload your own avatar:</label>
								<input type="file" id="custom-avatar" name="avatar" class="form-control"
								{% if user.avatar.url in predefined_avatars %}disabled{% endif %}>
							</div>

							<button type="submit" class="btn btn-primary w-100">Save Changes</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

mywebsite/frontend/templates/error_api.html
{% load static %}
<section class="d-flex align-items-center justify-content-center mt-5">
	<div class="container text-center">
		<div class="row justify-content-center">
			<div class="col-12 col-md-8 col-lg-6">
				<div class="card shadow p-4">
					<div class="card-body">
						<img src="{% static 'img/42_Logo.png' %}" alt="42 Logo" class="mb-4" style="width: 150px;">
						<h1 class="display-4 text-danger">Oops!</h1>
						<p class="lead">Something went wrong while communicating with the 42 API.</p>
						<p class="mb-4">We're sorry for the inconvenience. The service is currently unavailable. Please try again later or contact support if the issue persists.</p>

						<!-- <div class="alert alert-danger">
							<strong>Error Details:</strong>
							<p>{{ error_message }}</p>
						</div> -->

						<a href="/" class="btn btn-primary btn-lg mt-4" id="home-from-deleted">
							<i class="bi bi-house-door"></i> Back to Home
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

mywebsite/frontend/templates/profile.html
{% load static %}
<section class="d-flex align-items-center justify-content-center mt-5">
	<div class="container mb-5">
		<div class="row justify-content-center g-3">
			<!-- Profile Section -->
			<div class="col-12 col-lg-6 col-xxl-4">
				<div class="card shadow rounded-2">
					<div class="card-header text-center bg-primary font-balsamiq text-secondary-emphasis rounded-top-2 pt-3">
						<h2 class="fs-4">Profile</h2>
					</div>
					<div class="card-body p-5">
						<div class="text-center mb-4 text-center">
							<img src="{{ user.avatar.url }}" alt="{{ user.display_name }}'s Avatar" class="rounded-circle" width="120" height="120">
						</div>
						<div class="text-center">
							<a href="{% url 'user_dashboard' user.display_name %}" class="font-balsamiq text-secondary-emphasis fs-4 ms-2 mb-2 text-center">{{ user.display_name }}</a>
						</div>
						<p class="text-center mb-4 text-secondary-emphasis"><strong>{{ user.first_name }} {{ user.last_name }}</strong></p>
						<p class="text-center mb-4 text-secondary-emphasis"><strong>Email:</strong> {{ user.email }}</p>
						<div class="text-center d-flex justify-content-center flex-wrap">
							<a href="" class="btn btn-primary ms-2 mb-2" id="edit-profile" style="width: 140px;">Edit Profile</a>
							<a href="" class="btn btn-primary ms-2 mb-2" id="edit-password" style="width: 140px;">Edit Password</a>
							<form id="anonymize-data-form" method="POST" action="{% url 'authentification:request_anonymization' %}">
								{% csrf_token %}
								<button type="submit" class="btn btn-warning ms-2 mb-2 rounded-2 text-nowrap" style="width: 140px;" onclick="return confirm('Are you sure you want to anonymize your data? This action cannot be undone.');">Anonymize data</button>
							</form>
							<form id="delete-account-form" method="POST" action="{% url 'authentification:delete_profile' %}" class="d-inline">
								{% csrf_token %}
								<button type="submit" class="btn btn-danger ms-2 mb-2 rounded-2" style="width: 140px;" onclick="return confirm('Are you sure you want to delete your account?');">
									Delete account
								</button>
							</form>
						</div>
					</div>
				</div>
			</div>

			<!-- Friends Section -->
			<div class="col-12 col-lg-6 col-xxl-4">
				<div class="card shadow rounded-2">
					<div class="card-header text-center bg-primary font-balsamiq text-secondary-emphasis rounded-top-2 pt-3">
						<h2 class="fs-4">Friends</h2>
					</div>
					<div class="card-body p-4">
						<form id="add-friend-form" method="POST" action="{% url 'profile' %}">
							{% csrf_token %}
							<div class="input-group mb-3">
								<input id="receiver_display_name" type="text" name="receiver_display_name" class="form-control rounded-start-2" placeholder="Enter friend's username" required>
								<button type="submit" class="btn btn-primary rounded-start-0">Add Friend</button>
							</div>
						</form>

						{% if user.friend_list.friends.all %}
							<ul class="list-group">
								{% for friend in user.friend_list.friends.all %}
									<li class="list-group-item d-flex justify-content-between align-items-center rounded-1">
										<div>
											<img src="{{ friend.avatar.url }}" alt="{{ friend.display_name }}'s Avatar" class="rounded-circle me-2" width="40" height="40">
											<a href="{% url 'user_dashboard' friend.display_name %}" class="text-secondary-emphasis ms-2 mb-2">{{ friend.display_name }}</a>
										</div>
										<div>
											<span class="text-secondary-emphasis p-2">
												{{ friend.is_online|yesno:"Online,Offline" }}
											</span>
											<form method="POST" action="/auth/remove_friend/{{ friend.id }}/" class="d-inline remove-friend-form">
												{% csrf_token %}
												<button type="submit" class="btn btn-danger btn-sm rounded-1">Remove</button>
											</form>
										</div>
									</li>
								{% endfor %}
							</ul>
						{% else %}
							<p class="text-center text-secondary-emphasis" style="opacity: 0.7;">You have no friends added yet.</p>
						{% endif %}
					</div>
				</div>
			</div>

			<!-- Friend Invitations Section -->
			<div class="col-12 col-lg-6 col-xxl-4">
				<div class="card shadow rounded-2">
					<div class="card-header text-center bg-primary font-balsamiq text-secondary-emphasis rounded-top-2 pt-3">
						<h2 class="fs-4">Friend's Invitations</h2>
					</div>
					<div class="card-body p-4">
						<!-- Received Invitations -->
						<h4 class="text-center mb-3 text-secondary-emphasis">Received</h4>
						{% if pending_requests %}
							<ul class="list-group mb-4">
								{% for request in pending_requests %}
									<li class="list-group-item d-flex justify-content-between align-items-center rounded-3">
										<div>
											<img src="{{ request.sender.avatar.url }}" alt="{{ request.sender.display_name }}'s Avatar" class="rounded-circle me-2" width="40" height="40">
											<strong class="text-secondary-emphasis">{{ request.sender.display_name }}</strong>
										</div>
										<div>
											<form method="POST" action="/auth/accept_friend_request/{{ request.id }}/" class="d-inline accept-friend-request">
												{% csrf_token %}
												<button type="submit" class="btn btn-primary btn-sm rounded-2">Accept</button>
											</form>
											<form method="POST" action="/auth/refuse_friend_request/{{ request.id }}/" class="d-inline refuse-friend-request">
												{% csrf_token %}
												<button type="submit" class="btn btn-danger btn-sm rounded-2">Decline</button>
											</form>
										</div>
									</li>
								{% endfor %}
							</ul>
						{% else %}
							<p class="text-center text-secondary-emphasis" style="opacity: 0.7;">No pending friend requests.</p>
						{% endif %}

						<!-- Sent Invitations -->
						<h4 class="text-center mb-3 text-secondary-emphasis">Sent</h4>
						{% if sent_requests %}
							<ul class="list-group">
								{% for request in sent_requests %}
									<li class="list-group-item d-flex justify-content-between align-items-center rounded-3">
										<div>
											<img src="{{ request.receiver.avatar.url }}" alt="{{ request.receiver.display_name }}'s Avatar" class="rounded-circle me-2" width="40" height="40">
											<strong class="text-secondary-emphasis">{{ request.receiver.display_name }}</strong>
										</div>
										<div>
											<span class="text-secondary-emphasis">Pending...</span>
											<form method="POST" action="/auth/cancel_friend_request/{{ request.id }}/" class="d-inline cancel-friend-request">
												{% csrf_token %}
												<button type="submit" class="btn btn-danger btn-sm rounded-2">Cancel</button>
											</form>
										</div>
									</li>
								{% endfor %}
							</ul>
						{% else %}
							<p class="text-center text-secondary-emphasis" style="opacity: 0.7;">No sent friend requests.</p>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
</section>